//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBAS.Vault.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DBAS.Vault.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO Account
        ///(
        ///	Name,
        ///	TenantId,
        ///	ClientId,
        ///	ClientSecret
        ///)
        ///VALUES
        ///(
        ///	@Name,
        ///	@TenantId,
        ///	@ClientId,
        ///	@ClientSecret
        ///).
        /// </summary>
        public static string AccountService_Create {
            get {
                return ResourceManager.GetString("AccountService_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE Account SET DeletedAt = CURRENT_TIMESTAMP WHERE AccountId = @AccountId AND DeletedAt IS NULL.
        /// </summary>
        public static string AccountService_Delete {
            get {
                return ResourceManager.GetString("AccountService_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE SecretKey SET DeletedAt = CURRENT_TIMESTAMP WHERE AccountId = @AccountId AND DeletedAt IS NULL.
        /// </summary>
        public static string AccountService_DeleteAccountSecrets {
            get {
                return ResourceManager.GetString("AccountService_DeleteAccountSecrets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM Account WHERE AccountId = @AccountId AND DeletedAt IS NULL.
        /// </summary>
        public static string AccountService_Get {
            get {
                return ResourceManager.GetString("AccountService_Get", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM Account WHERE Name = @Name AND DeletedAt IS NULL.
        /// </summary>
        public static string AccountService_GetByName {
            get {
                return ResourceManager.GetString("AccountService_GetByName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE Account SET ClientSecret = @ClientSecret WHERE AccountId = @AccountId.
        /// </summary>
        public static string AccountService_UpdateClientSecret {
            get {
                return ResourceManager.GetString("AccountService_UpdateClientSecret", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application running and healthy with version {0}....
        /// </summary>
        public static string ApplicationRunningMessage {
            get {
                return ResourceManager.GetString("ApplicationRunningMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application is unhealhty with version {0} due to {1}..
        /// </summary>
        public static string ApplicationUnhealthyMessage {
            get {
                return ResourceManager.GetString("ApplicationUnhealthyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application failed to ping MySql host {0}:{1}..
        /// </summary>
        public static string ApplicationUnhealthyPingFailed {
            get {
                return ResourceManager.GetString("ApplicationUnhealthyPingFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server={0};Port={1};User ID={2};Password={3};{4};AllowPublicKeyRetrieval=True;SslMode=None;.
        /// </summary>
        public static string ConnectionString {
            get {
                return ResourceManager.GetString("ConnectionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE DATABASE IF NOT EXISTS {0}.
        /// </summary>
        public static string CreateDatabaseString {
            get {
                return ResourceManager.GetString("CreateDatabaseString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DBAS_Vault.
        /// </summary>
        public static string DatabaseName {
            get {
                return ResourceManager.GetString("DatabaseName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties/Scripts/DatabaseScript.sql.
        /// </summary>
        public static string DatabaseScriptFile {
            get {
                return ResourceManager.GetString("DatabaseScriptFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database={0}.
        /// </summary>
        public static string MySql_DatabaseNameString {
            get {
                return ResourceManager.GetString("MySql_DatabaseNameString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT LAST_INSERT_ID();.
        /// </summary>
        public static string MySql_GetLastInsertedId {
            get {
                return ResourceManager.GetString("MySql_GetLastInsertedId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to connect to mysql database &quot;{0}:{1}&quot; in &quot;{2}&quot;..
        /// </summary>
        public static string MySql_UnableToConnectMessage {
            get {
                return ResourceManager.GetString("MySql_UnableToConnectMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for MySql ({0}:{1}) to be healthy {2}/{3}... Message: {4}.
        /// </summary>
        public static string MySqlWaitingMessage {
            get {
                return ResourceManager.GetString("MySqlWaitingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;NULL&gt;.
        /// </summary>
        public static string NullRepresentation {
            get {
                return ResourceManager.GetString("NullRepresentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO SecretKey
        ///(
        ///	AccountId,
        ///	Name,
        ///	Description,
        ///	Version,
        ///	Value
        ///)
        ///VALUES
        ///(
        ///	@AccountId,
        ///	@Name,
        ///	@Description,
        ///	@Version,
        ///	@Value
        ///).
        /// </summary>
        public static string SecretService_Create {
            get {
                return ResourceManager.GetString("SecretService_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE SecretKey SET DeletedAt = CURRENT_TIMESTAMP WHERE AccountId = @AccountId AND Name = @Name AND DeletedAt IS NULL.
        /// </summary>
        public static string SecretService_Delete {
            get {
                return ResourceManager.GetString("SecretService_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT	SecretKey.*
        ///FROM	SecretKey
        ///	INNER JOIN
        ///	(
        ///		SELECT	AccountId,
        ///			Name,
        ///			MAX(SecretKeyId) AS LastId
        ///		FROM	SecretKey
        ///		GROUP BY
        ///			AccountId,
        ///			Name
        ///	) LastVersion
        ///		ON	SecretKey.AccountId = LastVersion.AccountId AND
        ///			SecretKey.Name = LastVersion.Name AND
        ///			SecretKey.SecretKeyId = LastVersion.LastId
        ///WHERE	SecretKey.AccountId = @AccountId AND
        ///	SecretKey.Name = @Name AND
        /// 	SecretKey.DeletedAt IS NULL.
        /// </summary>
        public static string SecretService_Get {
            get {
                return ResourceManager.GetString("SecretService_Get", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT	SecretKey.*
        ///FROM	SecretKey
        ///WHERE	AccountId = @AccountId AND Name = @Name AND Version = @Version AND DeletedAt IS NULL.
        /// </summary>
        public static string SecretService_GetVersion {
            get {
                return ResourceManager.GetString("SecretService_GetVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account ID &quot;{0}&quot; not found..
        /// </summary>
        public static string Service_AccountNotFound {
            get {
                return ResourceManager.GetString("Service_AccountNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secret &quot;{0}&quot; not found in account &quot;{1}&quot;..
        /// </summary>
        public static string Service_SecretNotFound {
            get {
                return ResourceManager.GetString("Service_SecretNotFound", resourceCulture);
            }
        }
    }
}
